package com.techeer.carpool.domain.expense;

import com.techeer.carpool.domain.application.entity.Application;
import com.techeer.carpool.domain.application.repository.ApplicationRepository;
import com.techeer.carpool.domain.meeting.MeetingService;
import com.techeer.carpool.domain.member.entity.Member;
import com.techeer.carpool.domain.member.repository.MemberRepository;
import com.techeer.carpool.domain.post.entity.Post;
import com.techeer.carpool.domain.post.entity.PostType;
import com.techeer.carpool.domain.post.repository.PostRepository;
import com.techeer.carpool.global.exception.CarpoolException;
import com.techeer.carpool.global.exception.ErrorCode;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.autoconfigure.EnableAutoConfiguration;
import org.springframework.boot.persistence.autoconfigure.EntityScan;
import org.springframework.boot.test.context.TestConfiguration;
import org.springframework.context.annotation.Import;
import org.springframework.data.jpa.repository.config.EnableJpaRepositories;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.annotation.DirtiesContext;
import org.springframework.test.context.DynamicPropertyRegistry;
import org.springframework.test.context.DynamicPropertySource;
import org.springframework.test.context.TestPropertySource;
import org.springframework.test.context.jdbc.Sql;
import org.springframework.test.context.junit.jupiter.SpringJUnitConfig;
import org.springframework.transaction.PlatformTransactionManager;
import org.springframework.transaction.support.TransactionTemplate;
import org.testcontainers.junit.jupiter.Container;
import org.testcontainers.junit.jupiter.Testcontainers;
import org.testcontainers.postgresql.PostgreSQLContainer;

import java.time.LocalDateTime;
import java.util.UUID;
import static org.assertj.core.api.Assertions.*;

@Testcontainers
@SpringJUnitConfig(ExpenseIntegrationTest.Config.class)
@DirtiesContext(classMode = DirtiesContext.ClassMode.AFTER_CLASS)
@TestPropertySource(properties = {"spring.jpa.hibernate.ddl-auto=create", "spring.flyway.enabled=false"})
@Sql(statements = {
        "CREATE TABLE IF NOT EXISTS meeting_attendance (post_id bigint REFERENCES posts(id), member_id bigint REFERENCES members(id), status varchar(20) NOT NULL CHECK(status IN ('MET','NO_SHOW')), updated_at timestamp NOT NULL, PRIMARY KEY(post_id,member_id))",
        "CREATE TABLE IF NOT EXISTS expenses (post_id bigint PRIMARY KEY REFERENCES posts(id), total integer NOT NULL CHECK(total>=0), updated_at timestamp NOT NULL)",
        "CREATE TABLE IF NOT EXISTS expense_shares (post_id bigint REFERENCES expenses(post_id), member_id bigint REFERENCES members(id), amount integer NOT NULL CHECK(amount>=0), collected boolean NOT NULL DEFAULT false, PRIMARY KEY(post_id,member_id))",
        "CREATE TABLE IF NOT EXISTS expense_audit (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, post_id bigint REFERENCES posts(id), actor_id bigint NOT NULL, action varchar(30) NOT NULL, detail varchar(300) NOT NULL, created_at timestamp NOT NULL)"
})
class ExpenseIntegrationTest {
    @Container static final PostgreSQLContainer postgres = new PostgreSQLContainer("postgres:15-alpine");
    @DynamicPropertySource static void database(DynamicPropertyRegistry props) {
        props.add("spring.datasource.url", postgres::getJdbcUrl);
        props.add("spring.datasource.username", postgres::getUsername);
        props.add("spring.datasource.password", postgres::getPassword);
        props.add("spring.datasource.driver-class-name", () -> "org.postgresql.Driver");
    }
    @TestConfiguration
    @EnableAutoConfiguration
    @EntityScan(basePackageClasses = {Post.class, Member.class, Application.class})
    @EnableJpaRepositories(basePackageClasses = {PostRepository.class, MemberRepository.class, ApplicationRepository.class})
    @Import({MeetingService.class, ExpenseService.class})
    static class Config { }
    @Autowired ExpenseService expenses;
    @Autowired MeetingService meetings;
    @Autowired MemberRepository members;
    @Autowired PostRepository posts;
    @Autowired ApplicationRepository applications;
    @Autowired PlatformTransactionManager transactions;
    @Autowired JdbcTemplate jdbc;
    long host, first, second, noShow, outsider, postId;

    @BeforeEach void participants() {
        host=member(); first=member(); second=member(); noShow=member(); outsider=member();
        postId=posts.save(Post.builder().memberId(host).title("택시 비용 분담").type(PostType.TAXI)
                .departureLocation("강남역").destinationLocation("판교역")
                .departureTime(LocalDateTime.now().plusMinutes(10)).maxPassengers(4).build()).getId();
        for(long id:new long[]{first,second,noShow}) new TransactionTemplate(transactions).executeWithoutResult(tx->{
            Post post=posts.findByIdAndDeletedFalseWithLock(postId).orElseThrow();
            Application application=Application.builder().postId(postId).applicantId(id).build();
            application.accept(); applications.save(application); post.incrementPassengers();
        });
    }
    long member() { return members.save(Member.builder().email(UUID.randomUUID()+"@test.com")
            .password("pw").nickname("참가자").build()).getId(); }
    void finishMeeting() {
        jdbc.update("UPDATE posts SET departure_time=? WHERE id=?",LocalDateTime.now().minusMinutes(1),postId);
        meetings.mark(postId,first,"MET",host);
        meetings.mark(postId,second,"MET",host);
        meetings.mark(postId,noShow,"NO_SHOW",host);
        meetings.complete(postId,host);
    }

    @Test void equalSplitAssignsRemainderToHostAndExcludesNoShow() {
        finishMeeting();
        ExpenseService.View result=expenses.setTotal(postId,10001,host);
        assertThat(result.total()).isEqualTo(10001);
        assertThat(result.shares()).hasSize(3);
        assertThat(result.shares()).filteredOn(ExpenseService.Share::host).extracting(ExpenseService.Share::amount).containsExactly(3335);
        assertThat(result.shares()).filteredOn(s->!s.host()).extracting(ExpenseService.Share::amount).containsExactly(3333,3333);
        assertThat(result.shares()).extracting(ExpenseService.Share::memberId).doesNotContain(noShow);
        assertThat(result.shares().stream().mapToInt(ExpenseService.Share::amount).sum()).isEqualTo(10001);
        assertThat(expenses.get(postId,first).total()).isEqualTo(10001);
    }

    @Test void collectionBlocksEditingUntilUndoAndEveryChangeIsAudited() {
        finishMeeting();
        expenses.setTotal(postId,10001,host);
        expenses.collect(postId,first,true,host);
        assertError(()->expenses.setTotal(postId,9000,host),ErrorCode.EXPENSE_INVALID_STATUS);
        assertThat(expenses.get(postId,host).total()).isEqualTo(10001);
        int auditSize=expenses.history(postId,host).size();
        expenses.collect(postId,first,true,host);
        assertThat(expenses.history(postId,host)).hasSize(auditSize);
        expenses.collect(postId,first,false,host);
        ExpenseService.View changed=expenses.setTotal(postId,9000,host);
        assertThat(changed.shares()).extracting(ExpenseService.Share::amount).containsExactly(3000,3000,3000);
        assertThat(expenses.history(postId,host)).extracting(ExpenseService.Audit::action)
                .containsExactly("TOTAL_CHANGED","COLLECTION_UNDONE","COLLECTED","TOTAL_CHANGED");
        assertThat(expenses.history(postId,host)).allMatch(entry->entry.actorId().equals(host));
        assertThat(expenses.history(postId,host).get(0).detail()).isEqualTo("10001 -> 9000");
    }

    @Test void outsidersCannotReadAndOnlyHostCanChangeOrCollect() {
        finishMeeting();
        assertError(()->expenses.get(postId,outsider),ErrorCode.MEETING_FORBIDDEN);
        assertError(()->expenses.history(postId,outsider),ErrorCode.MEETING_FORBIDDEN);
        assertError(()->expenses.setTotal(postId,10001,first),ErrorCode.MEETING_FORBIDDEN);
        expenses.setTotal(postId,10001,host);
        assertError(()->expenses.collect(postId,second,true,first),ErrorCode.MEETING_FORBIDDEN);
        assertError(()->expenses.collect(postId,host,true,host),ErrorCode.EXPENSE_INVALID_STATUS);
        assertError(()->expenses.collect(postId,noShow,true,host),ErrorCode.EXPENSE_INVALID_STATUS);
    }

    @Test void incompleteMeetingAndCarpoolCannotCreateTaxiExpense() {
        assertError(()->expenses.setTotal(postId,10001,host),ErrorCode.EXPENSE_INVALID_STATUS);
        assertThat(expenses.get(postId,host).total()).isNull();
        finishMeeting();
        assertError(()->expenses.setTotal(postId,-1,host),ErrorCode.EXPENSE_INVALID_STATUS);
        jdbc.update("UPDATE posts SET type='CARPOOL' WHERE id=?",postId);
        assertError(()->expenses.setTotal(postId,10001,host),ErrorCode.EXPENSE_INVALID_STATUS);
        assertThat(jdbc.queryForObject("SELECT count(*) FROM expenses WHERE post_id=?",Long.class,postId)).isZero();
    }

    private void assertError(Runnable action, ErrorCode code) {
        assertThatThrownBy(action::run).isInstanceOfSatisfying(CarpoolException.class,
                error->assertThat(error.getErrorCode()).isEqualTo(code));
    }
}
