CREATE TABLE notification_outbox (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    notification_id BIGINT NOT NULL UNIQUE,
    receiver_id BIGINT NOT NULL,
    payload TEXT NOT NULL,
    attempts INTEGER NOT NULL DEFAULT 0,
    available_at TIMESTAMP NOT NULL,
    lease_until TIMESTAMP,
    claim_token VARCHAR(36),
    published_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL
);
CREATE INDEX idx_outbox_delivery ON notification_outbox (published_at, available_at, lease_until);
CREATE INDEX idx_notification_inbox ON notifications (receiver_id, notification_id DESC);
