CREATE TABLE expenses (
    post_id bigint PRIMARY KEY REFERENCES posts(id),
    total integer NOT NULL CHECK (total >= 0),
    updated_at timestamp NOT NULL
);
CREATE TABLE expense_shares (
    post_id bigint NOT NULL REFERENCES expenses(post_id),
    member_id bigint NOT NULL REFERENCES members(id),
    amount integer NOT NULL CHECK (amount >= 0),
    collected boolean NOT NULL DEFAULT false,
    PRIMARY KEY (post_id, member_id)
);
CREATE TABLE expense_audit (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id bigint NOT NULL REFERENCES posts(id),
    actor_id bigint NOT NULL,
    action varchar(30) NOT NULL,
    detail varchar(300) NOT NULL,
    created_at timestamp NOT NULL
);
CREATE INDEX idx_expense_audit_post ON expense_audit(post_id, id);
