spring:
  main:
    lazy-initialization: true
  datasource:
    hikari:
      maximum-pool-size: 30
      minimum-idle: 5
      connection-timeout: 10000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

jwt:
  access-token-expiration: 900000
  refresh-token-expiration: 604800000
  cookie-secure: false
